# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GotronMcp < Formula
  desc "MCP server for TRON blockchain"
  homepage "https://gotron.sh"
  version "0.3.0"
  license "LGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.3.0/gotron-mcp_0.3.0_darwin_amd64.tar.gz"
      sha256 "33ab37335f625ffa7419b04d3e350bddeebc6caaa6130ff6e4e96ed2c354f6c6"

      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.3.0/gotron-mcp_0.3.0_darwin_arm64.tar.gz"
      sha256 "189410b4c9b35e2ed2f6bdd1de83bac20fff17d6c03a378cf30ee78e48cc236e"

      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.3.0/gotron-mcp_0.3.0_linux_amd64.tar.gz"
      sha256 "a30684f04bed56457c7ab475a527d2d66cb132d58307b7132240e84652817d27"
      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.3.0/gotron-mcp_0.3.0_linux_arm64.tar.gz"
      sha256 "5968fcaadf65b6c4e50d9a9851d78d647f59f742b44fcc531c4fd904d7a3d9b3"
      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
  end
end
