# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GotronMcp < Formula
  desc "MCP server for TRON blockchain"
  homepage "https://gotron.sh"
  version "0.1.0"
  license "LGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.1.0/gotron-mcp_0.1.0_darwin_amd64.tar.gz"
      sha256 "ced0dff6bb73b468a379d2179aa72b785e64d780f91bfb40a3874830eeb5d958"

      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.1.0/gotron-mcp_0.1.0_darwin_arm64.tar.gz"
      sha256 "63346a8c06b45d4fdce56c5042b95828940f44b6f76d7143f99914e2690bc44a"

      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.1.0/gotron-mcp_0.1.0_linux_amd64.tar.gz"
      sha256 "16e33f70795bd39304f6056f7bd7bf7df06455fbf8a6397fa9d914b489e93af6"
      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-mcp/releases/download/v0.1.0/gotron-mcp_0.1.0_linux_arm64.tar.gz"
      sha256 "182f55307f2dac9b7918b93c172570e6c1fb50213fdb245ccf554e9bb21a55ed"
      define_method(:install) do
        bin.install "gotron-mcp"
      end
    end
  end
end
