# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tronctl < Formula
  desc "Go SDK & CLI for TRON blockchain"
  homepage "https://gotron.sh"
  version "0.25.1"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.1/tronctl_0.25.1_darwin_amd64.tar.gz"
      sha256 "a0c1fc7a8edf287eb1fbea203a2b4ae077d804e384b0b6b3fc4cb0cf0a113789"

      define_method(:install) do
        bin.install "tronctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.1/tronctl_0.25.1_darwin_arm64.tar.gz"
      sha256 "a50b030a74e2d85184bffc2be3cebe6479362fc28b81d891661cec15df0c712b"

      define_method(:install) do
        bin.install "tronctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.1/tronctl_0.25.1_linux_amd64.tar.gz"
      sha256 "6a48b0bc8d97fbecf7ac95ef2b8f7dddcaabee7aab8aecab9a0c64176eee4171"
      define_method(:install) do
        bin.install "tronctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.1/tronctl_0.25.1_linux_arm64.tar.gz"
      sha256 "eba78ff031a7d3ddde7066cdccb8ccf5ad8e321d7f1e2e42a3098e812dd863fa"
      define_method(:install) do
        bin.install "tronctl"
      end
    end
  end

  test do
    system "#{bin}/tronctl", "version"
  end
end
