# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tronctl < Formula
  desc "Go SDK & CLI for TRON blockchain"
  homepage "https://gotron.sh"
  version "0.25.2"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.2/tronctl_0.25.2_darwin_amd64.tar.gz"
      sha256 "badaaac45eda387030449ebedcd98a7df432cd8931f0561c88c8f8847ceb168b"

      define_method(:install) do
        bin.install "tronctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.2/tronctl_0.25.2_darwin_arm64.tar.gz"
      sha256 "46beb49cd4b8941a428bdf468e3b528703e6bb4611343792b59e8982ccf3a6bb"

      define_method(:install) do
        bin.install "tronctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.2/tronctl_0.25.2_linux_amd64.tar.gz"
      sha256 "1d402b59f02ff0862dcf0c79b9a8690ba3eb176038f2761365337236cf115927"
      define_method(:install) do
        bin.install "tronctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fbsobreira/gotron-sdk/releases/download/v0.25.2/tronctl_0.25.2_linux_arm64.tar.gz"
      sha256 "255480ba3198b5c336648fe16db8c1c2e1130101541d00e40f405dc467b17d9d"
      define_method(:install) do
        bin.install "tronctl"
      end
    end
  end

  test do
    system "#{bin}/tronctl", "version"
  end
end
